import Head from 'next/head';
import Container from '@/containers/Container';
import { SettingsContent, getCareerCategoryContent, getCareerContent } from '@/helpers/data_utils';

function CareerInner() {
    return (
        <>
            <Head>
                <title>Career inner page</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main>
                <center>
                    <h1>Career inner page</h1>
                </center>
            </main>
        </>
    );
}

export default Container(CareerInner);

export async function getServerSideProps({ req, res }) {
    return {
        props: {
            settingsContent: await SettingsContent(),
            careerContent: await getCareerContent(),
            careerCategoryContent: await getCareerCategoryContent(),
        },
    };
}
