import Head from 'next/head';
import Container from '@/containers/Container';
import { SettingsContent, getCareerContentById, getCareerCategoryContent, getCareerContent } from '@/helpers/data_utils';
import CareerOpenPosition from '@/components/CareerOpenPosition';
function CareerInner(props) {
    const careerCategoryContent =
        typeof props.careerCategoryContent.data.careerCategory.content === 'string'
            ? JSON.parse(props.careerCategoryContent.data.careerCategory.content)
            : props.careerCategoryContent.data.careerCategory.content;
    return (
        <>
            <Head>
                <title>Career inner page</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main>
                <CareerOpenPosition careerCategoryContent={careerCategoryContent} />
            </main>
        </>
    );
}

export default Container(CareerInner);

export async function getServerSideProps({ params, req, res }) {
    const slug = params.slug;
    return {
        props: {
            settingsContent: await SettingsContent(),
            careerCategoryContent: await getCareerContentById(slug),
        },
    };
}
