import Head from 'next/head';
import Container from '@/containers/Container';
import { SettingsContent, ServiceContent } from '@/helpers/data_utils';

import ServicesTempOneBan from '@/components/ServicesTempOneBan/ServicesTempOneBan';
import ServicesDesignAgency from '@/components/ServicesDesignAgency/ServicesDesignAgency';
import StobWorkWithUs from '@/components/StobWorkWithUs/WorkWithUs';
import BuildReact from '@/components/BuildReact/BuildReact';
import StoStep from '@/components/StoStep/StoStep';
import ServicesFaq from '@/components/ServicesFaq/ServicesFaq';
import StobGetBusiness from '@/components/StobGetBusiness/StobGetBusiness';
import HomeSuccessProduct from '@/components/HomeSuccessProduct/HomeSuccessProduct';
import config from '@/helpers/config';

function ServiceDetails(props) {
    const serviceContent = props.serviceData.data.service;
    const serviceData = serviceContent?.content ? JSON.parse(serviceContent?.content) : '';
    const settingsContent = JSON.parse(props.settingsContent.data.settingsData.content);
    const metaTitle = props.metaTitle;
    const metaDescription = props.metaDescription;
    return (
        <>
            <Head>
                <title>{ metaTitle }</title>
                 <meta name="description" content={metaDescription} />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            {Number(serviceData?.banner?.status) === 1 && <ServicesTempOneBan serviceData={serviceData} settingsContent={settingsContent} />}
            {Number(serviceData?.section1?.status) === 1 && <StobGetBusiness serviceData={serviceData} />}
            {Number(serviceData?.section2?.status) === 1 && <ServicesDesignAgency serviceData={serviceData} />}
            {Number(serviceData?.section3?.status) === 1 && <StobWorkWithUs serviceData={serviceData} />}
            {Number(serviceData?.section4?.status) === 1 && <BuildReact serviceData={serviceData} />}
            {Number(serviceData?.section5?.status) === 1 && <StoStep serviceData={serviceData} />}
            {Number(serviceData?.section6?.status) === 1 && <ServicesFaq serviceData={serviceData} />}
            <HomeSuccessProduct />
        </>
    );
}
export default Container(ServiceDetails);

export async function getServerSideProps(context) {
    const { params, req, res } = context;
    const slug = params.slug;
    let metaTitle = 'Service detail page';
    let metaDescription = 'Generated by create next app';
    if(slug === 'web-application-development'){
        metaTitle = 'Web Application Development Services - Aqualeaf IT Solutions';
        metaDescription = "Aqualeaf IT Solutions provides top-notch web application development services tailored to meet modern businesses' requirements. Get in touch for a quote today!";
        
    }
    if(slug === 'api-development'){
        metaTitle = 'API Development Services - Aqualeaf IT Solutions';
        metaDescription = "Aqualeaf IT Solutions offers high-quality API development services that help businesses integrate with third-party applications and streamline their operations.";
        
    }
    if(slug === 'custom-solutions'){
        metaTitle = "Custom IT Solutions - Aqualeaf IT Solutions";
        metaDescription = "Aqualeaf IT Solutions provides custom IT solutions that cater to the unique needs of businesses. From development to deployment, we've got you covered! Call now!";
        
    }
    if(slug === 'mobile-app-development'){
        metaTitle = "Mobile App Development Services - Aqualeaf IT Solutions";
        metaDescription = "Aqualeaf IT Solutions offers mobile app development services that help businesses reach their target audience and increase their customer base. Get a quote now!";
        
    }
    if(slug === 'mvp-development'){
        metaTitle = "MVP Development Services - Aqualeaf IT Solutions";
        metaDescription = "Aqualeaf IT Solutions provides MVP development services that help businesses launch their products quickly and cost-effectively. Contact us today to learn more!";
        
    }
    if(slug === 'blockchain-technology'){
        metaTitle = "Blockchain Technology Services - Aqualeaf IT Solutions";
        metaDescription = "Aqualeaf IT Solutions offers cutting-edge blockchain technology services that help businesses improve transparency, security, and efficiency. Contact us for more information!";
        
    }
    if(slug === 'ecommerce-website'){
        metaTitle = "Ecommerce Website Development - Aqualeaf IT Solutions";
        metaDescription = "Aqualeaf IT Solutions provides ecommerce website development services that help businesses establish a robust online presence and boost sales. Get in touch today!";
        
    }
    if(slug === 'software-testing-qa'){
        metaTitle = "Software Testing & QA Services - Aqualeaf IT Solutions";
        metaDescription = "Aqualeaf IT Solutions offers software testing and quality assurance services that ensure your products are of the highest quality. Contact us for more information!";
        
    }
    
    return {
        props: {
            settingsContent: await SettingsContent(),
            serviceData: await ServiceContent(slug),
            metaTitle:metaTitle,
            metaDescription:metaDescription
            
        },
    };
}
